export const SHELL_SET_CURRENTROUTE = 'SHELL_SET_CURRENTROUTE'
export const SHELL_SET_TOGGLEISLOADING = 'SHELL_SET_TOGGLEISLOADING'

export const READER_SET_PATTERN = 'READER_SET_PATTERN'
export const READER_SET_DIRECTORY = 'READER_SET_DIRECTORY'

export const PROCESSOR_SET_XMLS = 'PROCESSOR_SET_XMLS'
export const PROCESSOR_SET_RAWXMLS = 'PROCESSOR_SET_RAWXMLS'
export const PROCESSOR_SET_MODELS = 'PROCESSOR_SET_MODELS'
export const PROCESSOR_SET_XMLUNIQUEPROPS = 'PROCESSOR_SET_XMLUNIQUEPROPS'
export const PROCESSOR_SET_XMLSBYMODEL = 'PROCESSOR_SET_XMLSBYMODEL'
export const PROCESSOR_SET_XMLPROPERTIES = 'PROCESSOR_SET_XMLPROPERTIES'
